-- AlterTable
ALTER TABLE "accounts" ALTER COLUMN "status" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "achievements" ALTER COLUMN "status" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "applications" ALTER COLUMN "status" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "assets" ALTER COLUMN "status" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "badges" ALTER COLUMN "status" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "battlepasses" ALTER COLUMN "status" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "bounties" ALTER COLUMN "status" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "chains" ALTER COLUMN "status" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "collections" ALTER COLUMN "status" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "commentsOnForms" ALTER COLUMN "status" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "commentsOnProfiles" ALTER COLUMN "status" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "communities" ALTER COLUMN "status" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "discussions" ALTER COLUMN "status" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "events" ALTER COLUMN "status" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "exchanges" ALTER COLUMN "status" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "files" ALTER COLUMN "status" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "formSubmissions" ALTER COLUMN "status" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "forms" ALTER COLUMN "key" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "title" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "status" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "gameActs" ALTER COLUMN "key" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "name" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "status" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "gameAreas" ALTER COLUMN "key" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "name" SET DATA TYPE VARCHAR(200),
ALTER COLUMN "status" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "gameBiomes" ALTER COLUMN "key" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "name" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "status" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "gameCharacterAbilities" ALTER COLUMN "key" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "name" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "status" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "gameCharacterClasses" ALTER COLUMN "key" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "name" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "status" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "gameCharacterGenders" ALTER COLUMN "key" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "name" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "status" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "gameCharacterPersonalities" ALTER COLUMN "key" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "name" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "status" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "gameCharacterSkills" ALTER COLUMN "key" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "name" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "status" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "gameCharacterTitles" ALTER COLUMN "key" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "name" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "status" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "gameCharacters" ALTER COLUMN "key" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "status" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "title" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "gameCharactersOnTeams" ALTER COLUMN "status" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "gameEnergies" ALTER COLUMN "key" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "name" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "status" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "gameEras" ALTER COLUMN "key" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "name" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "status" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "gameFactions" ALTER COLUMN "key" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "name" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "status" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "gameItemAffixes" ALTER COLUMN "key" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "name" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "status" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "gameItemAttributes" ALTER COLUMN "key" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "name" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "status" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "gameItemMaterials" ALTER COLUMN "key" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "name" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "status" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "gameItemRarities" ALTER COLUMN "key" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "name" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "status" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "gameItemSets" ALTER COLUMN "key" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "name" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "status" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "gameItemSkins" ALTER COLUMN "key" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "name" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "status" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "gameItemSlots" ALTER COLUMN "key" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "name" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "status" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "gameItemSpecificTypes" ALTER COLUMN "key" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "name" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "status" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "gameItemSubTypes" ALTER COLUMN "key" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "name" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "status" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "gameItemTypes" ALTER COLUMN "key" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "name" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "status" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "gameItemsOnProfiles" ALTER COLUMN "status" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "gameLores" ALTER COLUMN "key" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "name" SET DATA TYPE VARCHAR(200),
ALTER COLUMN "status" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "gamePlanets" ALTER COLUMN "key" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "name" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "status" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "gameRecipes" ALTER COLUMN "key" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "name" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "status" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "gameSeasons" ALTER COLUMN "key" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "name" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "status" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "gameSolarSystems" ALTER COLUMN "key" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "name" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "status" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "gameStars" ALTER COLUMN "key" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "name" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "status" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "gameStashes" ALTER COLUMN "key" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "name" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "status" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "gameTeams" ALTER COLUMN "key" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "title" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "status" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "gameUniverses" ALTER COLUMN "key" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "name" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "status" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "ideas" ALTER COLUMN "status" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "items" ALTER COLUMN "status" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "leaderboards" ALTER COLUMN "status" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "licenses" ALTER COLUMN "status" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "logs" ALTER COLUMN "status" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "marketPairs" ALTER COLUMN "status" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "markets" ALTER COLUMN "status" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "messages" ALTER COLUMN "status" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "metaverses" ALTER COLUMN "key" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "title" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "status" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "offers" ALTER COLUMN "status" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "orders" ALTER COLUMN "status" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "payments" ALTER COLUMN "status" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "permissionsOnRoles" ALTER COLUMN "status" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "products" ALTER COLUMN "status" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "type" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "profiles" ALTER COLUMN "status" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "projects" ALTER COLUMN "status" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "ratings" ALTER COLUMN "status" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "realms" ALTER COLUMN "status" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "recordUpdates" ALTER COLUMN "objectType" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "actionType" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "reason" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "recordUpdatesOnForms" ALTER COLUMN "status" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "recordUpdatesOnProfiles" ALTER COLUMN "status" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "referrals" ALTER COLUMN "status" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "reviews" ALTER COLUMN "status" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "roles" ALTER COLUMN "status" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "rolesOnProfiles" ALTER COLUMN "status" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "servers" ALTER COLUMN "status" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "suggestions" ALTER COLUMN "status" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "tags" ALTER COLUMN "status" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "tokens" ALTER COLUMN "status" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "tournaments" ALTER COLUMN "status" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "tradeIdeas" ALTER COLUMN "status" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "trades" ALTER COLUMN "status" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "transactions" ALTER COLUMN "status" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "votes" ALTER COLUMN "status" SET DATA TYPE VARCHAR(100);
